# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 08:50
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20161112_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
