# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20161213_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='upvoted_blogs',
            field=models.ManyToManyField(related_name='upvoted_blogs', to='blog.BlogData'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_image',
        ),
    ]
